### ISSUE TITLE
Failed to build L4

### ISSUE THREAD

**Issue by fxsheep** [kernkonzept/mk#1]
I'm having this error during building L4:
> Wide character in syswrite at /home/sheep/external/l4redev/sources/l4/tool/lib/L4/Image.pm line 294.
make[5]: *** [/home/sheep/external/l4redev/sources/l4/pkg/bootstrap/server/src/Make.rules:329：mbi_modules.o] Error 255

I'm following this guide: https://github.com/kernkonzept/manifest/wiki/LinuxVM
And the error happens at "Once configured, build L4Re like this:" step. Building guide for i386 has the same error.
Host:
cat /etc/lsb-release 
> DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"

**Comment by icedieler** [comment]
Hi,
looks like something is sneaking multibyte characters into the build process. Could you please provide the full build log and the output of "make report" as an attachement to this issue?
Thanks,
Matthias.

**Comment by fxsheep** [comment]
Here it is.
[log.txt](https://github.com/kernkonzept/mk/files/5765343/log.txt)
[report.txt](https://github.com/kernkonzept/mk/files/5765344/report.txt)
Speaking of `multibyte characters`, this host uses zh-CN which has 2 bytes per character.

**Comment by icedieler** [comment]
Thank you. We will have a look into it.

**Comment by alacko** [comment]
Hi @fxsheep, I could not reproduce your problem, however, still improved things in the area. Could you please retry? Thanks.

**Comment by icedieler** [comment]
I consider this issue resolved.

**Comment by 512yottabytes** [comment]
Hello,
Have the same error:
`Wide character in syswrite at /home/512yb/src/l4re-base-21.04.0/src/l4/tool/lib/L4/Image.pm line 302.`
The line 302 at Image.pm:
`syswrite($fd, $buf, length($buf));`
How to solve it?

**Comment by alacko** [comment]
Could you please show me the output of 'locale' and which Linux distribution you are using? And does you name, login or hostname contain non-english characters?
